class PythonByte:
    def __init__(self, value: int): ...
    def __repr__(self): ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def __mul__(self, other): ...
    def __truediv__(self, other): ...
    def __floordiv__(self, other): ...
    def __rshift__(self, other): ...
    def __lshift__(self, other): ...
    def __xor__(self, other): ...
    def __or__(self, other): ...
    def __and__(self, other): ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    ...


class Color:
    red: PythonByte
    blue: PythonByte
    green: PythonByte
    ...


def rusty(x: int) -> int: ...


class FftResults:
    ...
    def get_max_amplitude(self) -> int: ...


fft_result: FftResults
